language: objective-c
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - node_modules/
branches:
    # Don't build these branches/tags
    except:
        # These are triggered manually
        - /^nightly-.*$/
env:
    - BUILD_TYPE=android
# Be a good travis citizen while we don't actually run the build on iOS yet.
#    - BUILD_TYPE=ios
before_install:
    - brew update
    - git clone https://github.com/creationix/nvm.git /tmp/.nvm
    - source /tmp/.nvm/nvm.sh
    - nvm install 5.0
    - nvm use --delete-prefix 5.0
    - node --version && npm --version
install:
    - . build-scripts/bootstrap.sh
script:
    - ./build-scripts/build.sh
    - env
deploy:
    provider: releases
    api_key: $GITHUB_AUTH_TOKEN
    file: $ARTIFACT
    skip_cleanup: true
    overwrite: true
    on:
        tags: false
        # Only deploy if a nightly build or a release (semver tag)
        condition: $TAG -eq "nightly-android" || $TAG -eq "nightly-ios" || $TAG =~ ^[0-9]+\.[0-9]+\.[0-9]
